import express, { Application, Request, Response, NextFunction  } from 'express';
import bodyParser from 'body-parser';
import swaggerUi from 'swagger-ui-express';
import swaggerJsdoc from 'swagger-jsdoc';
import path from 'path';
import morgan from 'morgan';

import * as db from './config/database';
import routes from './routes'

const app: Application = express();

db.connect();

app.use(function(req: Request, res: Response, next: NextFunction) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    if ('OPTIONS' === req.method) {
        res.sendStatus(200);
        return;
    }
    next();
});  
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false  }));
app.use(morgan('dev'));
app.use(routes());


const options = {
    swaggerDefinition: {
      info: {
        title: 'Test API',
        version: '1.0.0',
        description: 'Test Express API with autogenerated swagger doc',
      },
    },
    apis: [path.join(__dirname, './routes/*.route.ts')],
}
const specs = swaggerJsdoc(options)
app.use('/docs', swaggerUi.serve, swaggerUi.setup(specs));

app.listen(3000, () => console.log('Server running...'))